ilmSalohiyat/Areas/Manager/ViewModels/Teacher/EditImageViewModel.cs
namespace ilmSalohiyat.Areas.Manager.ViewModels.Teacher
{
    public class EditImageViewModel : UploadImageViewModel
    {
        public int Id { get; set; }
        public string ExistingImage { get; set; }
    }
}

ilmSalohiyat/Areas/Manager/ViewModels/Teacher/TeacherViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ilmSalohiyat.Areas.Manager.ViewModels.Teacher
{
    public class TeacherViewModel : EditImageViewModel
    {
        [Required]
        public string Firstname { get; set; }

        [Required]
        public string Lastname { get; set; }

        [Required]
        public string Description { get; set; }
    }
}

ilmSalohiyat/Areas/Manager/ViewModels/Teacher/UploadImageViewModel.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;

namespace ilmSalohiyat.Areas.Manager.ViewModels.Teacher
{
    public class UploadImageViewModel
    {
        [Required]
        [Display(Name = "Image")]
        public IFormFile TeacherPicture { get; set; }
    }
}

ilmSalohiyat/Models/Teacher.cs
using System.ComponentModel.DataAnnotations;

namespace ilmSalohiyat.Models
{
    public class Teacher
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Firstname { get; set; }

        [Required]
        public string Lastname { get; set; }

        [Required]
        public string ImageURL { get; set; }

        [Required]
        public string Description { get; set; }

    }
}

ilmSalohiyat/Areas/Manager/Controllers/TeachersController.cs
using ilmSalohiyat.Areas.Manager.ViewModels.Teacher;
using ilmSalohiyat.Data;
using ilmSalohiyat.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ilmSalohiyat.Areas.Manager.Controllers
{
    [Area("Manager")]
    public class TeachersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment webHostEnvironment;

        public TeachersController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            webHostEnvironment = hostEnvironment;
        }

        // GET: Teachers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Teachers.ToListAsync());
        }

        // GET: Teachers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers
                .FirstOrDefaultAsync(m => m.Id == id);
            var teacherViewModel = new TeacherViewModel()
            {
                Id = teacher.Id,
                Firstname = teacher.Firstname,
                Lastname = teacher.Lastname,
                Description = teacher.Description,
                ExistingImage = teacher.ImageURL
            };
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacherViewModel);
        }

        // GET: Teachers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Teachers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TeacherViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFilename = ProcessUploadedFile(model);
                Teacher teacher = new Teacher
                {
                    Firstname = model.Firstname,
                    Lastname = model.Lastname,
                    Description = model.Description,
                    ImageURL = uniqueFilename
                };
                _context.Teachers.Add(teacher);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: Teachers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers.FindAsync(id);
            var teacherViewModel = new TeacherViewModel()
            {
                Id = teacher.Id,
                Firstname = teacher.Firstname,
                Lastname = teacher.Lastname,
                Description = teacher.Description,
                ExistingImage = teacher.ImageURL
            };
            if (teacher == null)
            {
                return NotFound();
            }
            return View(teacherViewModel);
        }

        // POST: Teachers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, TeacherViewModel model)
        {
            if (ModelState.IsValid)
            {
                var teacher = await _context.Teachers.FindAsync(model.Id);
                teacher.Firstname = model.Firstname;
                teacher.Lastname = model.Lastname;
                teacher.Description = model.Description;

                if (model.TeacherPicture != null)
                {
                    if (model.ExistingImage != null)
                    {
                        string filePath = Path.Combine(webHostEnvironment.WebRootPath, "img", model.ExistingImage);
                        System.IO.File.Delete(filePath);
                    }
                    teacher.ImageURL = ProcessUploadedFile(model);
                }
                _context.Teachers.Update(teacher);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        // GET: Teachers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers
                .FirstOrDefaultAsync(m => m.Id == id);
            var teacherViewModel = new TeacherViewModel()
            {
                Id = teacher.Id,
                Firstname = teacher.Firstname,
                Lastname = teacher.Lastname,
                Description = teacher.Description,
                ExistingImage = teacher.ImageURL
            };
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacherViewModel);
        }

        // POST: Teachers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var teacher = await _context.Teachers.FindAsync(id);
            var CurrectImage = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", teacher.ImageURL);
            _context.Teachers.Remove(teacher);
            if (await _context.SaveChangesAsync() > 0)
            {
                if (System.IO.File.Exists(CurrectImage))
                {
                    System.IO.File.Delete(CurrectImage);
                }
            }
            return RedirectToAction(nameof(Index));
        }

        private bool teacherExists(int id)
        {
            return _context.Teachers.Any(e => e.Id == id);
        }

        private string ProcessUploadedFile(TeacherViewModel model)
        {
            string uniqueFileName = null;

            if (model.TeacherPicture != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "img");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.TeacherPicture.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.TeacherPicture.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }
    }
}

ilmSalohiyat/Controllers/CoursesController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ilmSalohiyat.Data;

namespace ilmSalohiyat.Controllers
{
    public class CoursesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CoursesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {
            return View(await _context.Courses.ToListAsync());
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        
    }
}

ilmSalohiyat/Controllers/TeachersController.cs
using ilmSalohiyat.Areas.Manager.ViewModels.Teacher;
using ilmSalohiyat.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace ilmSalohiyat.Controllers
{
    public class TeachersController : Controller
    {
        private readonly ApplicationDbContext _applicationDbContext;

        public TeachersController(ApplicationDbContext applicationDbContext)
        {
            _applicationDbContext = applicationDbContext;
        }

        // GET: Teachers
        public async Task<IActionResult> Index()
        {
            return View(await _applicationDbContext.Teachers.ToListAsync());
        }

        // GET: Teachers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _applicationDbContext.Teachers
                .FirstOrDefaultAsync(m => m.Id == id);
            var teacherViewModel = new TeacherViewModel()
            {
                Id = teacher.Id,
                Firstname = teacher.Firstname,
                Lastname = teacher.Lastname,
                Description = teacher.Description,
                ExistingImage = teacher.ImageURL
            };
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacherViewModel);
        }
    }
}

ilmSalohiyat/Areas/Manager/Views/Teachers/Create.cshtml
@model ilmSalohiyat.Areas.Manager.ViewModels.Teacher.TeacherViewModel

@{
    ViewData["Title"] = "Create";
}

<div class="card">
    <div class="card-header">
        <h3 class="text-uppercase">Новый учитель</h3>
    </div>
    <div class="card-body">
        <form asp-action="Create" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Firstname" class="control-label">Имя</label>
                        <input asp-for="Firstname" class="form-control" />
                        <span asp-validation-for="Firstname" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="TeacherPicture" class="control-label">Изображение</label>
                        <div class="custom-file">
                            <input asp-for="TeacherPicture" class="custom-file-input" />
                            <label class="custom-file-label" for="customFile">Choose file</label>
                        </div>
                        <span asp-validation-for="TeacherPicture" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Lastname" class="control-label">Фамилия</label>
                        <input asp-for="Lastname" class="form-control" />
                        <span asp-validation-for="Lastname" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Description" class="control-label">Описания</label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-sm btn-primary rounded-0" />
                <a asp-area="manager" asp-controller="Teachers" asp-action="Index" class="btn btn-sm btn-primary rounded-0">Назад</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        // Add the following code if you want the name of the file appear on select
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ilmSalohiyat/Areas/Manager/Views/Teachers/Delete.cshtml
@model ilmSalohiyat.Areas.Manager.ViewModels.Teacher.TeacherViewModel

@{
    ViewData["Title"] = "Delete";
}

<div class="alert alert-danger">
    <h3>Are you sure you want to delete this?</h3>
</div>
<div class="card">
    <div class="card-header">
        <h3 class="text-uppercase">Delete Teacher</h3>
    </div>
    <div class="card-body">
        <dl class="row">
            <dt class="col-sm-2">
                Имя
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Firstname)
            </dd>
            <dt class="col-sm-2">
                Фамилия
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Lastname)
            </dd>
            <dt class="col-sm-2">
                Описания
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class="col-sm-2">
                Изображение
            </dt>
            <dd class="col-sm-10">
                <img src="~/img/@Model.ExistingImage" class="img-thumbnail" height="100" width="100" asp-append-version="true" />
            </dd>
        </dl>
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <button type="submit" class="btn btn-sm btn-danger rounded-0"><i class="fa fa-trash-alt"></i> Delete</button>
            <a asp-area="manager" asp-controller="Courses" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-sm btn-info rounded-0"><i class="fa fa-pencil-alt"></i>Редактировать</a>
            <a asp-area="manager" asp-controller="Courses" asp-action="Index" class="btn btn-sm btn-primary rounded-0"><i class="fas fa-fast-backward"></i>Назад</a>
        </form>
    </div>
</div>

ilmSalohiyat/Areas/Manager/Views/Teachers/Details.cshtml
@model ilmSalohiyat.Areas.Manager.ViewModels.Teacher.TeacherViewModel

@{
    ViewData["Title"] = "Details";
}

<div class="card">
    <div class="card-header">
        <h3 class="text-uppercase">Подробности</h3>
    </div>
    <div class="card-body">
        <dl class="row">
            <dt class="col-sm-2">
                Имя
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Firstname)
            </dd>
            <dt class="col-sm-2">
                Фамилия
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Lastname)
            </dd>
            <dt class="col-sm-2">
                Описания
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class="col-sm-2">
                Изображение
            </dt>
            <dd class="col-sm-10">
                <img src="~/img/@Model.ExistingImage" class="img-thumbnail" height="100" width="100" asp-append-version="true" />
            </dd>
        </dl>
        <div>
            <a asp-area="manager" asp-controller="Courses" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-sm btn-info rounded-0"><i class="fa fa-pencil-alt"></i>Редактировать</a>
            <a asp-area="manager" asp-controller="Courses" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-sm btn-danger rounded-0"><i class="fa fa-trash-alt"></i>Удалить</a>
            <a asp-area="manager" asp-controller="Courses" asp-action="Index" class="btn btn-sm btn-primary rounded-0"><i class="fas fa-fast-backward"></i>Назад</a>
        </div>
    </div>
</div>

ilmSalohiyat/Areas/Manager/Views/Teachers/Edit.cshtml
@model ilmSalohiyat.Areas.Manager.ViewModels.Teacher.TeacherViewModel

@{
    ViewData["Title"] = "Edit";
}

<div class="card">
    <div class="card-header">
        <h3 class="text-uppercase">Редактировать</h3>
    </div>
    <div class="card-body">
        <form asp-action="Edit" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Firstname" class="control-label">Имя</label>
                        <input asp-for="Firstname" class="form-control" />
                        <span asp-validation-for="Firstname" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="TeacherPicture" class="control-label">Изображение</label>
                        <div class="custom-file">
                            <input asp-for="TeacherPicture" class="custom-file-input" />
                            <label class="custom-file-label" for="customFile">Choose file</label>
                        </div>
                        <span asp-validation-for="TeacherPicture" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Lastname" class="control-label">Фамилия</label>
                        <input asp-for="Lastname" class="form-control" />
                        <span asp-validation-for="Lastname" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Description" class="control-label">Описания</label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-sm btn-info rounded-0"><i class="fa fa-pencil-alt"></i>Обновить</button>
                <a asp-area="manager" asp-controller="Courses" asp-action="Index" class="btn btn-sm btn-primary rounded-0"><i class="fas fa-fast-backward"></i>Назад</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        // Add the following code if you want the name of the file appear on select
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ilmSalohiyat/Areas/Manager/Views/Teachers/Index.cshtml
@model IEnumerable<ilmSalohiyat.Models.Teacher>

@{
    ViewData["Title"] = "Index";
}

<h3 class="text-center text-uppercase">Учителя</h3>

<p>
    <a asp-action="Create" class="btn btn-primary rounded-0"><i class="fa fa-plus-circle"></i>Добавить нового учителя</a>
</p>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Изображение</th>
            <th>Имя</th>
            <th>Фамилия</th>
            <th>Описания</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">
                        <img src="~/img/@item.ImageURL" class="img-thumbnail" height="100" width="100" asp-append-version="true" />
                    </a>
                </td>
                <td>@item.Firstname</td>
                <td>@item.Lastname</td>
                <td>@item.Description</td>
                <td>
                    <a asp-area="manager" asp-controller="Teachers" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-info rounded-0"><i class="fa fa-pencil-alt">Изменить</i></a>
                    <a asp-area="manager" asp-controller="Teachers" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger rounded-0"><i class="fa fa-trash-alt">Удалить</i></a>
                </td>
            </tr>
        }
    </tbody>
</table>